config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'index' => 'home#index'
  get 'authentication' => 'home#authentication'

  devise_for :users 

  resources :projects

  devise_scope :user do
    get 'sign_in' => 'devise/sessions#new'
    delete 'sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  enum posting_genre: { planning: 0, skills: 1 }

  with_options presence: true do
    validates :title, length: { maximum: 20 }
    validates :description, length: { maximum: 140 }
    validates :posting_genre
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :projects

  enum occupation: { planner: 0, engineer: 1, designer: 2 }
  enum mochivation: { no_mochivation: 0, little_no_mochivation: 1, normal_mochivation: 2, pretty_mochivation: 3, max_mochivation: 4 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) do |user_params|
        user_params.permit(:login, :username, :email, :password, :remember_me, :graduation_year, :occupation, :mochivation)
      end
      devise_parameter_sanitizer.permit(:sign_in) do |user_params|
        user_params.permit(:email, :password, :remember_me)
      end
      devise_parameter_sanitizer.permit(:account_update) do |user_params|
        user_params.permit(:username, :email, :password, :password_confirmation, :current_password)
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index
    @projects = Project.all
    @user = User.all
  end

  def sign_in
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :create, :update, :destroy]
  before_action :set_project, only: [:update, :destroy]

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)
    #@project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { redirect_to root_path, notice: '投稿できませんでした'}
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :posting_genre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/_tab_layout.html.erb
<div>
  <ul class="nav nav-tabs" role="tablist">
    <li class="active" role="presentation">
      <a aria-controls="tab_a" data-toggle="tab" href="#tab_a" role="tab">全体</a>
    </li>
    <li role="presentation">
      <a aria-controls="tab_b" data-toggle="tab" href="#tab_b" role="tab">企画</a>
    </li>
    <li role="presentation">
      <a aria-controls="tab_c" data-toggle="tab" href="#tab_c" role="tab">スキル</a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab_a" role="tabpanel">
      <p>
        <% @projects.each do |project| %>
          <p>
            <strong>ユーザ名</strong><br>
            <%= @user.find(project.user_id).username %><br>
            <strong>投稿ジャンル</strong><br>
            <%= project.posting_genre_i18n %><br>
            <strong>投稿タイトル</strong><br>
            <%= project.title %><br>
            <strong>投稿内容</strong><br>
            <%= simple_format(project.description) %><br>
          </p>
          <hr>
        <% end %>
      </p>
    </div>
    <div class="tab-pane" id="tab_b" role="tabpanel">
      <p>
        <% @projects.each do |project| %>
          <% if project.posting_genre == "planning" then %>
            <p>
              <strong>ユーザ名</strong><br>
              <%= @user.find(project.user_id).username %><br>
              <strong>投稿ジャンル</strong><br>
              <%= project.posting_genre_i18n %><br>
              <strong>投稿タイトル</strong><br>
              <%= project.title %><br>
              <strong>投稿内容</strong><br>
              <%= simple_format(project.description) %><br>
            </p>
            <hr>
          <% end %>
        <% end %>
      </p>
    </div>
    <div class="tab-pane" id="tab_c" role="tabpanel">
      <p>
        <% @projects.each do |project| %>
          <% if project.posting_genre == "skills" then %>
            <p>
              <strong>ユーザ名</strong><br>
              <%= @user.find(project.user_id).username %><br>
              <strong>投稿ジャンル</strong><br>
              <%= project.posting_genre_i18n %><br>
              <strong>投稿タイトル</strong><br>
              <%= project.title %><br>
              <strong>投稿内容</strong><br>
              <%= simple_format(project.description) %><br>
            </p>
            <hr>
          <% end %>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/home/authentication.html.erb
<h1>Home#authentication</h1>
<p>Find me in app/views/home/authentication.html.erb</p>

app/views/home/index.html.erb
<html>
  <head>
    <title>このゆびとまれ</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "このゆびとまれ", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Log in", '#' %></li>
            <li><%= link_to "Log out", sign_out_path, method: :delete %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <p id="notice"><%= notice %></p>
      <%= form_with(model: Project.new, local: true, url: projects_path) do |f| %>
        <div class="field">
          <%= f.label "投稿タイトル" %><br/>
          <%= f.text_field :title, autofocus: true, size: 40 %>
        </div>
      
        <div class="field">
          <%= f.label "投稿内容" %><br/>
          <%= f.text_area :description, autofocus: true, cols: 40, rows: 5 %>
        </div>
        <div class="field">
          <%= f.label "投稿ジャンル" %><br/>
          <%= f.radio_button :posting_genre, :planning %> 企画
          <%= f.radio_button :posting_genre, :skills %> スキル
        </div>
      
        <div class="actions">
          <%= f.submit "投稿" %><br/>
        </div>
      <% end %>
      <%= render "tab_layout" %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Konoyubitomare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>